name: build

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 2

    - name: configure fpga-toolchain
      run: |
        export VERSION=nightly-20200930
        wget https://github.com/open-tool-forge/fpga-toolchain/releases/download/$VERSION/fpga-toolchain-linux_x86_64-$VERSION.tar.xz
        tar -xf fpga-toolchain-linux_x86_64-$VERSION.tar.xz
        rm -rf fpga-toolchain-linux_x86_64-$VERSION.tar.xz
        echo "$(pwd)/fpga-toolchain/bin" >> $GITHUB_PATH

    - name: configure riscv-toolchain
      run: |
        wget https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-ubuntu14.tar.gz
        tar -xzf riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-ubuntu14.tar.gz
        rm -rf riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-ubuntu14.tar.gz
        echo "$(pwd)/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-ubuntu14/bin" >> $GITHUB_PATH

    - name: Build
      working-directory: ./hw
      run: |
        python3 -m pip install Pillow
        yosys -V
        nextpnr-ecp5 -V
        python3 foboot-bitstream.py --platform orangecrab --revision 0.2
        pwd
        ls -R build

    - name: Upload bitstream
      uses: actions/upload-artifact@v2
      with:
        name: OrangeCrab Foboot Bitstream
        path: $GITHUB_WORKSPACE/hw/build/gateware/foboot.bit

      