name: build

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 2

    - name: configure fpga-toolchain
      run: |
        export VERSION=nightly-20200930
        wget https://github.com/open-tool-forge/fpga-toolchain/releases/download/$VERSION/fpga-toolchain-linux_x86_64-$VERSION.tar.xz
        tar -xf fpga-toolchain-linux_x86_64-$VERSION.tar.xz
        rm -rf fpga-toolchain-linux_x86_64-$VERSION.tar.xz
        echo "$(pwd)/fpga-toolchain/bin" >> $GITHUB_PATH

    - name: Build
      working-directory: ./hw
      run: |
        yosys -V
        nextpnr-ecp5 -V
        python3 foboot-bitstream.py --platform orangecrab --revision 0.2

      